// 此文件由构建脚本自动生成，请勿手动修改
// This file is auto-generated by build script, do not edit manually
// Build time: 2025-08-10T23:58:24+08:00

export const buildInfo = {
    buildTime: "2025-08-10T23:58:24+08:00",
    gitCommit: "669b1b8",
    gitBranch: "master",
};

export default buildInfo;