// 此文件由构建脚本自动生成，请勿手动修改
// This file is auto-generated by build script, do not edit manually
// Build time: 2025-08-09T23:42:50+08:00

export const buildInfo = {
    buildTime: "2025-08-09T23:42:50+08:00",
    gitCommit: "38a1817",
    gitBranch: "master",
};

export default buildInfo;